### PR TITLE
fix: missing coin details in assetDetails page

### LINKED ISSUE #2862: After I revoked tx in multisig header is disappearing in Tx details.
**Describe the bug**
After I revoked tx in multisig header is disappearing in Tx details. Also header can disappear from main account page from time to time:

**To Reproduce**
1. Go to multisig tx
2. Revoke Tx
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF 
 -  - Version 123

**Additional context**
Reproducible in FF extension

multi

### LINKED ISSUE #2863: Coin details data is showing not full info, also there is no url that leads user to coingecko page
**Describe the bug**
Coin details data is showing not full info, also there is no url that leads user to coingecko page

**To Reproduce**
1. Go to Coin details page
2. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser. FF
 - Version 123

**Additional context**
Reproducible on release branch, FF ext. 

coin det

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2863 
closes #2862

### CODE REVIEW

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
Sometimes it could be broken, especially on multisig details coin info page: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/036ca3b4-554a-418e-a842-7fd35a1fff60

**Comment by Liubov-crypto** [comment]
For me this issue is still reproducible. I noticed that this could be caused by multisig proposal Tx: 


https://github.com/superhero-com/superhero-wallet/assets/69896204/c53b9c0e-94c4-4ee8-ae1b-6596ad0bfbd2


https://github.com/superhero-com/superhero-wallet/assets/69896204/88f1ce14-3977-41c4-bebc-7fcac9cf08a5

**Comment by Liubov-crypto** [comment]
Could this be caused by mdw issue 400 and limit=30? 

https://github.com/superhero-com/superhero-wallet/assets/69896204/8552d625-b4f2-4ae0-9a2c-a7436eb9882d


https://github.com/superhero-com/superhero-wallet/assets/69896204/3aea2bb2-719d-48fb-896d-b314629d0283



errr
errrrs

**Comment by Liubov-crypto** [comment]
> Could this be caused by mdw issue 400 and limit=30?
> 
>  2024-03-22.3.40.01.mov 
>  2024-03-22.3.41.36.mov 
> 
> 
> errr errrrs

Today it's working for me as expected. I haven't received mdw 400 and limit=30 issues. LGTM

**Review by CedrikNikita — APPROVED** [review]

**Pull request merged**
