### PR TITLE
Release v2.2.9

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Review by martinkaintas — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
1. Ending height (≈ day) is missing day/hours data (same on prod): 

https://github.com/user-attachments/assets/ebf5a087-7773-474f-949c-23f9d10cfa67

2. Spacing: 
bid

**Comment by Liubov-crypto** [comment]
LGTM

**Comment by dvdbak** [comment]
image
https://release-v2-2-9.wallet.z52da5wt.xyz/more/settings/seed-phrase/details/verify

**Comment by Liubov-crypto** [comment]
Fix is LGTM

**Pull request merged**
