### PR TITLE
Release v2.2.3

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Review by peronczyk — APPROVED** [review]

**Review by martinkaintas — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
During the testing I found these "flying" bugs: 

1. Multisig info is displaying not fully. Stepts to reproduce it: 
- create new multisig 
- propose tx
- observe an issue:

multi
multi1

https://github.com/superhero-com/superhero-wallet/assets/69896204/4cf032b5-7908-47f8-9523-2d96e4e9b00c

2. Accounts counter could be missing from time to time:

фсс


3. Fiat value could be missing from time to time:

fiat

4. After I applied secure login by fingerprint I was not able to login via pin code. And it looks like secure login via finger print isn't working on my android device: 


https://github.com/superhero-com/superhero-wallet/assets/69896204/cf262b17-b587-4086-8af6-cb78ea7a7be7

**Comment by dvdbak** [comment]
I do have the same issue #4 like Liubov on my Samsung S10. After successful authentication the Wallet got locked again, but hitting the back button the Wallet is visible.

**Comment by Liubov-crypto** [comment]
Ios app:
1. Security login was stop working on ios app for some reason. The first login via FaceID was succesful, the next ones are not: 


https://github.com/superhero-com/superhero-wallet/assets/69896204/07a78952-ccda-4a33-b6b2-3807b28c04c6

2. Proposing multisig Tx was stuck forever (2 attempts) but after work normally: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/1d808c00-a8fe-4ebb-87cb-e9fd0414c65d

**Comment by CedrikNikita** [comment]
> 2. Accounts counter could be missing from time to time:

Counter is shown if user have more then 5 accounts.
https://github.com/superhero-com/superhero-wallet/blob/1ec471a47756e6064b140c189df8ce6507388a01/src/popup/components/DashboardBase.vue#L19

**Comment by Liubov-crypto** [comment]
Proposing multisig Tx was stuck forever (2 attempts) but after work normally - this issue could be related to fact that I have on accounts signer stuck Tx, so it's affect other Tx related to multisig proposal.

**Comment by Liubov-crypto** [comment]
This issue has been fixed: 
Ios app:

Security login was stop working on ios app for some reason. The first login via FaceID was succesful, the next ones are not:

**Review by Liubov-crypto — APPROVED** [review]
LGTM

**Pull request merged**
