### PR TITLE
fix: get correct dryAeSdk after changing network

### LINKED ISSUE #2479: Can't create multisig in the testnet
**Describe the bug**
Can't create multisig in the testnet on dev branch.

**To Reproduce**
1. Click on Create multisig vault in the testnet
2. Choose signer 1 and signer 2
3. Click on Confirm

**Desktop (please complete the following information):**
 - OS: MacOS 12.7
 - Browser: FF, Chrome
 

**Additional context**
Reproducible in testnet on dev branch. 

Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2479

### CODE REVIEW

**Review by peronczyk — CHANGES_REQUESTED** [review]

**Review by peronczyk — APPROVED** [review]

**Comment by CedrikNikita** [comment]
Both the issue you are trying to fix and #2541 is based on fact that `networkName` is not being restored yet. I don't think that this exact place needed to be fixed. And `await` is not an async action if the `networkId` was already asked.

**Comment by Liubov-crypto** [comment]
In general it's working. 
But sometimes I was not able to create vault especially in FF extension because of bad data fetching - I saw balances from mainnet in the testnet which is not correct. 

ff ext
v3err



https://github.com/superhero-com/superhero-wallet/assets/69896204/ac5eb48a-411d-4f49-bcb2-63140a00d0c7

**Comment by martinkaintas** [comment]
Turns out the problem was not fixed in #2561. Reopening this PR since it fixes the issue.
**Steps to reproduce the issue:** 
- Reset wallet
- Change to testnet
- Try to create  multisig wallet

**This currently doesn't work on develop but should be fixed with this PR**

**Comment by Liubov-crypto** [comment]
Fixed, LGTM

**Pull request merged**
