### PR TITLE
Release v2.2.11

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Review by Liubov-crypto — CHANGES_REQUESTED** [review]
I've found some small issues: 

1. When Tx / name is in pending status there should be 3 dots instead of 6: 
pen2

pen1

2. Bidding details: 

bid

3. No redirection to URL, however it supposed to be by design:

https://github.com/user-attachments/assets/005775d3-da6b-4982-ae3e-670b42769562

**Review by dvdbak — APPROVED** [review]
LGTM regression tests passed

**Comment by Liubov-crypto** [comment]
I've tested web and briefly extensions: 

1. When I'm opening the last multisig accounts it redirects my automatically to my 1st multisig account in web wallet (it's not reproducible in extensions): 

https://github.com/user-attachments/assets/d69ac965-5105-46b0-8c01-81dfe4e5dfb5

2. when Tx is in pending status: 
un

un1

**Review by martinkaintas — APPROVED** [review]

**Review by peronczyk — APPROVED** [review]

**Review by onvisions — APPROVED** [review]

**Review by dvdbak — APPROVED** [review]
Approved

**Review by smaroudasunicorn — APPROVED** [review]

**Pull request merged**
