### PR TITLE
Hotfix: backend links, fix deeplinks issues

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Review by martinkaintas — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
1. After creating a new vault, it takes a very long time to synchronize (more than 10 minutes):


https://github.com/superhero-com/superhero-wallet/assets/69896204/53d659d4-3c54-4d24-b9b4-cbd20d135fb6


2. If I send tokens to it and then offer a transaction, it will be impossible to cancel or approve this transaction. also the balance will be zero, although there will be an incoming one in the list of transactions:


https://github.com/superhero-com/superhero-wallet/assets/69896204/833b95f3-bab7-4159-9e57-7ac70ea4d2bf

lval


3. if I propose a transaction from an empty vault, then the pending transaction will not be visible:

https://github.com/superhero-com/superhero-wallet/assets/69896204/aa664774-37ac-47b0-8058-e79856ac524f

4. There is a black gap at the bottom in the vault details

**Comment by Liubov-crypto** [comment]
3 and 4 have been fixed. 

1 and 2 are still reproducible. 2 is caused by long-time synchronization.

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
Fixed, LGTM.

**Comment by Liubov-crypto** [comment]
LGTM. I can create vault in both networks. They are working fine, I can top up it and propose/revoke/decline/send Transaction. 
Names auctions also looks fine.

**Comment by Liubov-crypto** [comment]
Android apk: 
1. Cropped text on multisig vault card: 
2024-02-01 4 56 20 пп

2. Multisig creation has been failed few times on testnet, but then I was able to create a vault: 

2024-02-01 4 56 35 пп

3. Appload screen: 
2024-02-01 4 56 43 пп

I think these are not UI bugs, just icon and contract address are placed differently, probably depends on device screen: 


2024-02-01 4 56 51 пп
2024-02-01 4 56 56 пп

**Comment by Liubov-crypto** [comment]
iOS app: 

1. Tx list is displaying partly in new ios app. is this could be related to pending tx? (the fix is not applied yet)

https://github.com/superhero-com/superhero-wallet/assets/69896204/2ba441ef-d107-4284-beba-b21e88d9ede8

2. Transactions are displaying with huge delay in Multisig Tx list. Almost 12 minutes passed before they appeared on the list.

3. I can see Ae transactions in FT transactions list: 

2024-02-02 12 05 40 пп

4. If I'm adding custom permissions then delete it, and will add it again I will see my previous (deleted) permission:


https://github.com/superhero-com/superhero-wallet/assets/69896204/413c48fc-4b90-47ac-8b9c-0be28ba21e90

**Comment by Liubov-crypto** [comment]
Retested deeplinks implementation, LGTM

**Review by Liubov-crypto — APPROVED** [review]
LGTM

**Review by smaroudasunicorn — APPROVED** [review]

**Review by dvdbak — COMMENTED** [review]
LGTM

**Comment by Liubov-crypto** [comment]
iOS app:

1. I can't sign any deeplink in app. I was redirected to web browser instead. 

2. Tx list is displaying partly from time to time in new ios app.

3. I was disconnected after submitting Tx on DEX. It happens from time to time:

https://github.com/superhero-com/superhero-wallet/assets/69896204/bdbfd772-f441-4a16-a26b-1190e9c44777

4. If I'm adding custom permissions then delete it, and will add it again I will see my previous (deleted) permission.

**Pull request merged**
