### PR TITLE
Release v2.2.0

### PR DESCRIPTION
**Pull request by CedrikNikita**

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
Related issues: 

https://github.com/orgs/superhero-com/projects/2/views/2?pane=issue&itemId=57110992


https://github.com/orgs/superhero-com/projects/2/views/2?pane=issue&itemId=57111289

https://github.com/orgs/superhero-com/projects/2/views/2?pane=issue&itemId=57111774

**Comment by Liubov-crypto** [comment]
Related issues:
#2887 
#2888 
#2885 
#2879 
#2880
#2883 

some of them also reproducible on ios app

**Comment by Liubov-crypto** [comment]
Related issues:

#2907 
#2889 
#2912 
#2920 
#2921 

iOS app:
#2919 

not merged: 
#2878

**Review by onvisions — APPROVED** [review]

**Review by peronczyk — APPROVED** [review]

**Review by smaroudasunicorn — APPROVED** [review]

**Review by martinkaintas — APPROVED** [review]

**Comment by dvdbak** [comment]
LGTM

**Pull request merged**
